observation = [
  {
    "is_canceled": 0,
    "lead_time": 210,
    "arrival_date_year": 2017,
    "arrival_date_month": 7.0,
    "arrival_date_week_number": 35,
    "arrival_date_day_of_month": 28,
    "stays_in_weekend_nights": 2,
    "stays_in_week_nights": 5,
    "adults": 2,
    "children": 0.0,
    "babies": 0,
    "previous_cancellations": 0,
    "previous_bookings_not_canceled": 0,
    "reserved_room_type": 0.0,
    "assigned_room_type": 0.0,
    "booking_changes": 0,
    "days_in_waiting_list": 0,
    "adr": 85.59,
    "required_car_parking_spaces": 0,
    "total_of_special_requests": 1,
    "has_company": 1.0,
    "has_agent": 0.0,
    "reservation_status_Canceled": 0.0,
    "reservation_status_Check-Out": 1.0,
    "reservation_status_No-Show": 0.0,
    "customer_type_Contract": 0.0,
    "customer_type_Group": 0.0,
    "customer_type_Transient": 1.0,
    "customer_type_Transient-Party": 0.0,
    "deposit_type_No Deposit": 1.0,
    "deposit_type_Non Refund": 0.0,
    "deposit_type_Refundable": 0.0,
    "market_segment_Aviation": 0.0,
    "market_segment_Complementary": 0.0,
    "market_segment_Corporate": 0.0,
    "market_segment_Direct": 0.0,
    "market_segment_Groups": 0.0,
    "market_segment_Offline TA/TO": 0.0,
    "market_segment_Online TA": 1.0,
    "market_segment_Undefined": 0.0,
    "distribution_channel_Corporate": 0.0,
    "distribution_channel_Direct": 0.0,
    "distribution_channel_GDS": 0.0,
    "distribution_channel_TA/TO": 1.0,
    "distribution_channel_Undefined": 0.0,
    "meal_BB": 1.0,
    "meal_FB": 0.0,
    "meal_HB": 0.0,
    "meal_SC": 0.0,
    "meal_Undefined": 0.0,
    "got_higher_type_room": 0.0,
    "got_lower_type_room": 0.0,
    "_yhat_": 0.9999427199363708,
    "_label_": "XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,\n              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,\n              importance_type='gain', interaction_constraints=None,\n              learning_rate=0.300000012, max_delta_step=0, max_depth=6,\n              min_child_weight=1, missing=nan, monotone_constraints=None,\n              n_estimators=100, n_jobs=0, num_parallel_tree=1,\n              objective='binary:logistic', random_state=0, reg_alpha=0,\n              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,\n              validate_parameters=False, verbosity=None)",
    "_ids_": 0,
    "_y_": 0
  }
];