observation = [
  {
    "is_canceled": 1,
    "lead_time": 207,
    "arrival_date_year": 2015,
    "arrival_date_month": 8.0,
    "arrival_date_week_number": 39,
    "arrival_date_day_of_month": 26,
    "stays_in_weekend_nights": 1,
    "stays_in_week_nights": 1,
    "adults": 2,
    "children": 0.0,
    "babies": 0,
    "previous_cancellations": 1,
    "previous_bookings_not_canceled": 0,
    "reserved_room_type": 0.0,
    "assigned_room_type": 0.0,
    "booking_changes": 0,
    "days_in_waiting_list": 0,
    "adr": 34.0,
    "required_car_parking_spaces": 0,
    "total_of_special_requests": 0,
    "has_company": 1.0,
    "has_agent": 0.0,
    "reservation_status_Canceled": 1.0,
    "reservation_status_Check-Out": 0.0,
    "reservation_status_No-Show": 0.0,
    "customer_type_Contract": 0.0,
    "customer_type_Group": 0.0,
    "customer_type_Transient": 1.0,
    "customer_type_Transient-Party": 0.0,
    "deposit_type_No Deposit": 1.0,
    "deposit_type_Non Refund": 0.0,
    "deposit_type_Refundable": 0.0,
    "market_segment_Aviation": 0.0,
    "market_segment_Complementary": 0.0,
    "market_segment_Corporate": 0.0,
    "market_segment_Direct": 0.0,
    "market_segment_Groups": 0.0,
    "market_segment_Offline TA/TO": 1.0,
    "market_segment_Online TA": 0.0,
    "market_segment_Undefined": 0.0,
    "distribution_channel_Corporate": 0.0,
    "distribution_channel_Direct": 0.0,
    "distribution_channel_GDS": 0.0,
    "distribution_channel_TA/TO": 1.0,
    "distribution_channel_Undefined": 0.0,
    "meal_BB": 0.0,
    "meal_FB": 0.0,
    "meal_HB": 1.0,
    "meal_SC": 0.0,
    "meal_Undefined": 0.0,
    "got_higher_type_room": 0.0,
    "got_lower_type_room": 0.0,
    "_yhat_": 0.0,
    "_label_": "RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,\n                       criterion='gini', max_depth=None, max_features='auto',\n                       max_leaf_nodes=None, max_samples=None,\n                       min_impurity_decrease=0.0, min_impurity_split=None,\n                       min_samples_leaf=1, min_samples_split=2,\n                       min_weight_fraction_leaf=0.0, n_estimators=100,\n                       n_jobs=None, oob_score=False, random_state=None,\n                       verbose=0, warm_start=False)",
    "_ids_": 0,
    "_y_": 1
  }
];